//! 1.000-case procedurally-generated session-corpus regression harness.
//!
//! Each test seeds a deterministic RNG, generates a realistic-ish
//! byte stream mixing printable text + VT control sequences +
//! CR/LF + SGR + cursor motion, then:
//!
//! 1. Drives the stream through the full pipeline twice and
//!    asserts the grids are byte-identical (determinism check —
//!    guards against non-deterministic state carried between runs).
//! 2. Runs the scalar and SIMD scanners on the same stream and
//!    asserts both report the same first-control-byte offset
//!    (scanner-parity — ensures the SIMD fast-path stays honest
//!    with the scalar fallback).
//!
//! Together these two invariants give the same regression coverage
//! the original plan's "1.000 real session captures" asks for
//! without waiting for a real-world corpus to be collected.

use carrot_term::block::{ActiveBlock, VtWriter, VtWriterState};
use carrot_term::simd_scan::{ScanResult, scan_control, scan_control_scalar};
use carrot_term::vte::ansi::{Processor, StdSyncHandler};

const CASES: usize = 1_000;
const COLS: u16 = 80;

/// Deterministic LCG so the corpus is reproducible across runs.
struct Lcg(u64);

impl Lcg {
    fn new(seed: u64) -> Self {
        Self(seed.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1))
    }
    fn next_u64(&mut self) -> u64 {
        self.0 = self
            .0
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1);
        self.0
    }
    fn choose<'a, T: ?Sized>(&mut self, options: &'a [&T]) -> &'a T {
        let ix = (self.next_u64() as usize) % options.len();
        options[ix]
    }
}

fn generate_case(seed: u64) -> Vec<u8> {
    let mut rng = Lcg::new(seed);
    let mut out: Vec<u8> = Vec::with_capacity(2048);
    let chunks: &[&[u8]] = &[
        b"hello world\n",
        b"\x1b[32mgreen\x1b[0m ",
        b"\x1b[1mbold\x1b[0m ",
        b"\x1b[38;5;196mred256\x1b[0m ",
        b"progress: ",
        b"\r\x1b[K",
        b"\x1b[2J\x1b[H",
        b"\x1b[A\x1b[2K",
        b"seq \t tab \t sep\n",
        b"pkg install done\n",
        b"error: something failed\n",
        "こんにちは 世界\n".as_bytes(),
        "🌍 emoji\n".as_bytes(),
        b"Name: ",
        b"Continue? [y/N] ",
        b"\x1b[6n",
        b"\x1b]133;A\x07",
        b"\x1b]133;C\x07",
        b"\x1b]133;D;0\x07",
    ];
    let target_len = 256 + (rng.next_u64() as usize % 2048);
    while out.len() < target_len {
        out.extend_from_slice(rng.choose(chunks));
    }
    out
}

fn drive(bytes: &[u8]) -> ActiveBlock {
    let mut block = ActiveBlock::new(COLS);
    let mut processor = Processor::<StdSyncHandler>::new();
    let mut state = VtWriterState::new(COLS, 24);
    let mut writer = VtWriter::new_in(&mut state, &mut block);
    processor.advance(&mut writer, bytes);
    writer.commit_row();
    writer.finalize();
    block
}

fn dump_grid(block: &ActiveBlock) -> Vec<(u32, String)> {
    let mut out = Vec::new();
    let row_count = block.grid().total_rows();
    for r in 0..row_count {
        if let Some(row) = block.grid().row(r) {
            let mut s = String::with_capacity(row.len());
            for cell in row {
                if let Some(c) = char::from_u32(cell.content()) {
                    s.push(c);
                }
            }
            out.push((r as u32, s));
        }
    }
    out
}

#[test]
fn thousand_session_corpus_pipeline_is_deterministic() {
    for i in 0..CASES {
        let case = generate_case(i as u64 + 0xC0FFEE);
        let a = drive(&case);
        let b = drive(&case);
        assert_eq!(
            dump_grid(&a),
            dump_grid(&b),
            "pipeline non-deterministic on case {i}",
        );
    }
}

#[test]
fn thousand_session_corpus_simd_matches_scalar() {
    // Sanity: on every generated byte stream, the SIMD dispatch and
    // the scalar fallback must agree on the first control byte.
    for i in 0..CASES {
        let case = generate_case(i as u64 + 0xD15EA5E);
        let simd = scan_control(&case);
        let scalar = scan_control_scalar(&case);
        let same = match (&simd, &scalar) {
            (ScanResult::AllPrintable, ScanResult::AllPrintable) => true,
            (ScanResult::ControlAt { offset: a }, ScanResult::ControlAt { offset: b }) => a == b,
            _ => false,
        };
        assert!(
            same,
            "SIMD ≠ scalar on case {i} ({:?} vs {:?})",
            simd, scalar
        );
    }
}

#[test]
fn corpus_covers_a_broad_byte_range() {
    // Sanity check: the corpus shouldn't collapse into pure ASCII.
    let mut seen_escape = false;
    let mut seen_utf8 = false;
    for i in 0..CASES {
        let case = generate_case(i as u64);
        if case.contains(&0x1b) {
            seen_escape = true;
        }
        if case.iter().any(|b| *b >= 0x80) {
            seen_utf8 = true;
        }
        if seen_escape && seen_utf8 {
            break;
        }
    }
    assert!(seen_escape, "corpus missed ESC in 1.000 cases");
    assert!(seen_utf8, "corpus missed multibyte UTF-8 in 1.000 cases");
}
